### PR TITLE
fix #740

### LINKED ISSUE #740: Model input shape in word embedding example
Hi, 

Trying the word embedding example on this post: https://www.r-bloggers.com/word-embeddings-with-keras/. Wonderful example while can not get it work on both windows and unbuntu:

**code (the same as the post):**

```
download.file("https://snap.stanford.edu/data/finefoods.txt.gz", "finefoods.txt.gz")
library(readr)
library(stringr)
reviews <- read_lines("finefoods.txt.gz") 
reviews <- reviews[str_sub(reviews, 1, 12) == "review/text:"]
reviews <- str_sub(reviews, start = 14)
reviews <- iconv(reviews, to = "UTF-8")
head(reviews, 2)
library(keras)
tokenizer <- text_tokenizer(num_words = 20000)
tokenizer %>% fit_text_tokenizer(reviews)

library(reticulate)
library(purrr)
skipgrams_generator <- function(text, tokenizer, window_size, negative_samples) {
  gen <- texts_to_sequences_generator(tokenizer, sample(text))
  function() {
    skip <- generator_next(gen) %>%
      skipgrams(
        vocabulary_size = tokenizer$num_words, 
        window_size = window_size, 
        negative_samples = 1
      )
    x <- transpose(skip$couples) %>% map(. %>% unlist %>% as.matrix(ncol = 1))
    y <- skip$labels %>% as.matrix(ncol = 1)
    list(x, y)
  }
}

embedding_size <- 128  # Dimension of the embedding vector.
skip_window <- 5       # How many words to consider left and right.
num_sampled <- 1       # Number of negative examples to sample for each word.

input_target <- layer_input(shape = 1)
input_context <- layer_input(shape = 1)

embedding <- layer_embedding(
  input_dim = tokenizer$num_words + 1, 
  output_dim = embedding_size, 
  input_length = 1, 
  name = "embedding"
)

target_vector <- input_target %>% 
  embedding() %>% 
  layer_flatten()

context_vector <- input_context %>%
  embedding() %>%
  layer_flatten()

dot_product <- layer_dot(list(target_vector, context_vector), axes = 1)
output <- layer_dense(dot_product, units = 1, activation = "sigmoid")

model <- keras_model(list(input_target, input_context), output)
model %>% compile(loss = "binary_crossentropy", optimizer = "adam")

model %>%
  fit_generator(
    skipgrams_generator(reviews, tokenizer, skip_window, negative_samples), 
    steps_per_epoch = 100000, epochs = 5
  )

**Error:** 

13. | stop(structure(list(message = "ValueError: Error when checking model input: the list of Numpy arrays that you are passing to your model is not the size the model expected. Expected to see 2 array(s), but instead got the following list of 1 arrays: [array([[[ 2485],\n        [  261],\n        [   38],\n        ...,\n        [   38],\n        [    1],\n        [   12]],\n\n       [[ 6959],\n        [   53],\n        [10595],\n        ...,\n        [ 2485],\n ...",      call = py_call_impl(callable, dots$args, dots$keywords),      cppstack = structure(list(file = "", line = -1L, stack = "C++ stack not available on this system"), .Names = c("file",      "line", "stack"), class = "Rcpp_stack_trace")), .Names = c("message",  ...
-- | --
```

```
**Session Info:**

sessionInfo() R version 3.4.3 (2017-11-30) Platform: x86_64-w64-mingw32/x64 (64-bit) Running under: Windows >= 8 x64 (build 9200)  Matrix products: default  locale: [1] LC_COLLATE=Chinese (Simplified)_China.936  LC_CTYPE=Chinese (Simplified)_China.936    LC_MONETARY=Chinese (Simplified)_China.936 LC_NUMERIC=C                               [5] LC_TIME=Chinese (Simplified)_China.936      attached base packages: [1] stats     graphics  grDevices utils     datasets  methods   base       other attached packages: [1] purrr_0.2.4            reticulate_1.12.0-9000 stringr_1.2.0          readr_1.1.1            keras_2.2.4.1           loaded via a namespace (and not attached):  [1] Rcpp_1.0.1        whisker_0.3-2     magrittr_1.5      hms_0.4.1         devtools_1.13.5   lattice_0.20-35   R6_2.2.2          rlang_0.1.6       tools_3.4.3       grid_3.4.3        withr_2.1.1       [12] tfruns_1.4        yaml_2.1.16       digest_0.6.13     tibble_1.4.1      tensorflow_1.13.1 Matrix_1.2-12     base64enc_0.1-3   zeallot_0.1.0     memoise_1.1.0     stringi_1.1.6     compiler_3.4.3    [23] pillar_1.0.1      generics_0.0.2    jsonlite_1.6      pkgconfig_2.0.1
--
 
> | >
>
```
Any help greatly appreciated.

### PR DESCRIPTION
**Pull request by dfalbel**
Fix bug with function generators when the model has multiple inputs.

### CODE REVIEW

File: tests/testthat/test-generators.R [hunk 1]
```diff
@@ -119,3 +119,21 @@ test_succeeds("R function can be used as custom generator", {
    
 })
 
+test_succeeds("R function can be used as custom generato with multiple inputs", {
```
Comment (skeydan) [inline tests/testthat/test-generators.R]: so cool you fixed this :-)
just spotted a missing "r" (from "generator")
